version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    config:
      threshold: 150
  identical-code:
    config:
      threshold: 100
  method-complexity:
    config:
      threshold: 15

plugins:
  # Python
  radon:
    enabled: true
    config:
      threshold: "C"
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:

  # Other
  git-legal:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
