language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  # Login to docker hub
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

install: "pip install .[test]"

script: "pytest --cov=learnosity_sdk"

notifications:
  slack:
    rooms:
      secure: tCs/NWSyAvBa6GiyVp9Bkn/tyqEe6rWddw/XQvLHeZgPFI5433Nxycus1lxlp9ugASPdDDjKEiHXDRE64km1g3mGOyiRDald0n5z3aTYb4lebBxVjD9uKvJhjwknEmmEvaQV9UfP6hq8muX0Yx3qjhNNYZve8FR8UCFl3YC68mc=
    on_success: change
